// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace MPCRS
{
    public partial class PredectiveEnginePerformance
    {
        /// <summary>
        /// model input class for PredectiveEnginePerformance.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"P1")]
            public float P1 { get; set; }

            [ColumnName(@"T1")]
            public float T1 { get; set; }

            [ColumnName(@"P2")]
            public float P2 { get; set; }

            [ColumnName(@"T2")]
            public float T2 { get; set; }

            [ColumnName(@"P2B")]
            public float P2B { get; set; }

            [ColumnName(@"P3")]
            public float P3 { get; set; }

            [ColumnName(@"T3")]
            public float T3 { get; set; }

            [ColumnName(@"T5")]
            public float T5 { get; set; }

            [ColumnName(@"P6")]
            public float P6 { get; set; }

            [ColumnName(@"T6")]
            public float T6 { get; set; }

            [ColumnName(@"P6B")]
            public float P6B { get; set; }

            [ColumnName(@"T6B")]
            public float T6B { get; set; }

            [ColumnName(@"NH")]
            public float NH { get; set; }

            [ColumnName(@"NL")]
            public float NL { get; set; }

            [ColumnName(@"WF")]
            public float WF { get; set; }

            [ColumnName(@"XG")]
            public float XG { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for PredectiveEnginePerformance.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"P1")]
            public float P1 { get; set; }

            [ColumnName(@"T1")]
            public float T1 { get; set; }

            [ColumnName(@"P2")]
            public float P2 { get; set; }

            [ColumnName(@"T2")]
            public float T2 { get; set; }

            [ColumnName(@"P2B")]
            public float P2B { get; set; }

            [ColumnName(@"P3")]
            public float P3 { get; set; }

            [ColumnName(@"T3")]
            public float T3 { get; set; }

            [ColumnName(@"T5")]
            public float T5 { get; set; }

            [ColumnName(@"P6")]
            public float P6 { get; set; }

            [ColumnName(@"T6")]
            public float T6 { get; set; }

            [ColumnName(@"P6B")]
            public float P6B { get; set; }

            [ColumnName(@"T6B")]
            public float T6B { get; set; }

            [ColumnName(@"NH")]
            public float NH { get; set; }

            [ColumnName(@"NL")]
            public float NL { get; set; }

            [ColumnName(@"WF")]
            public float WF { get; set; }

            [ColumnName(@"XG")]
            public float XG { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("PredectiveEnginePerformance.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
