﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.FastTree;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace MPCRS
{
    public partial class PredectiveEnginePerformance
    {
        /// <summary>
        /// Retrains model using the pipeline generated as part of the training process. For more information on how to load data, see aka.ms/loaddata.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainPipeline(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"P1", @"P1"),new InputOutputColumnPair(@"T1", @"T1"),new InputOutputColumnPair(@"P2", @"P2"),new InputOutputColumnPair(@"T2", @"T2"),new InputOutputColumnPair(@"P2B", @"P2B"),new InputOutputColumnPair(@"P3", @"P3"),new InputOutputColumnPair(@"T3", @"T3"),new InputOutputColumnPair(@"T5", @"T5"),new InputOutputColumnPair(@"P6", @"P6"),new InputOutputColumnPair(@"T6", @"T6"),new InputOutputColumnPair(@"P6B", @"P6B"),new InputOutputColumnPair(@"T6B", @"T6B"),new InputOutputColumnPair(@"NH", @"NH"),new InputOutputColumnPair(@"NL", @"NL"),new InputOutputColumnPair(@"WF", @"WF")})      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"P1",@"T1",@"P2",@"T2",@"P2B",@"P3",@"T3",@"T5",@"P6",@"T6",@"P6B",@"T6B",@"NH",@"NL",@"WF"}))      
                                    .Append(mlContext.Regression.Trainers.FastTree(new FastTreeRegressionTrainer.Options(){NumberOfLeaves=61,MinimumExampleCountPerLeaf=126,NumberOfTrees=485,MaximumBinCountPerFeature=1022,FeatureFraction=0.937661607510145,LearningRate=0.999999776672986,LabelColumnName=@"XG",FeatureColumnName=@"Features"}));

            return pipeline;
        }
    }
}
